# Generated by Django 3.2.4 on 2021-06-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentmen',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='garmentothers',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='garmentwomen',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
    ]
