# Generated by Django 3.2.4 on 2021-07-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_auto_20210616_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmentmen',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='garmentmen',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garmentothers',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garmentwomen',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
