# Generated by Django 3.2.4 on 2021-07-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_auto_20210710_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garmentmen',
            old_name='score',
            new_name='combined_score',
        ),
        migrations.RenameField(
            model_name='garmentothers',
            old_name='score',
            new_name='combined_score',
        ),
        migrations.RenameField(
            model_name='garmentwomen',
            old_name='score',
            new_name='combined_score',
        ),
        migrations.RemoveField(
            model_name='garmentmen',
            name='count_for_each_ranking',
        ),
        migrations.RemoveField(
            model_name='garmentothers',
            name='count_for_each_ranking',
        ),
        migrations.RemoveField(
            model_name='garmentwomen',
            name='count_for_each_ranking',
        ),
        migrations.CreateModel(
            name='WomenGarmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('UN', 'Prefer not to say')], max_length=100)),
                ('count_for_each_ranking', models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0})),
                ('score', models.IntegerField(default=0)),
                ('garment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.garmentwomen')),
            ],
            options={
                'unique_together': {('garment_id', 'user_gender')},
            },
        ),
        migrations.CreateModel(
            name='OtherGarmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('UN', 'Prefer not to say')], max_length=100)),
                ('count_for_each_ranking', models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0})),
                ('score', models.IntegerField(default=0)),
                ('garment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.garmentothers')),
            ],
            options={
                'unique_together': {('garment_id', 'user_gender')},
            },
        ),
        migrations.CreateModel(
            name='MenGarmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('UN', 'Prefer not to say')], max_length=100)),
                ('count_for_each_ranking', models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0})),
                ('score', models.IntegerField(default=0)),
                ('garment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.garmentmen')),
            ],
            options={
                'unique_together': {('garment_id', 'user_gender')},
            },
        ),
    ]
