# Generated by Django 3.2.4 on 2021-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0004_auto_20210715_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentmen',
            name='combined_count_for_each_ranking',
            field=models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0}),
        ),
        migrations.AddField(
            model_name='garmentothers',
            name='combined_count_for_each_ranking',
            field=models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0}),
        ),
        migrations.AddField(
            model_name='garmentwomen',
            name='combined_count_for_each_ranking',
            field=models.JSONField(default={'rank_1': 0, 'rank_10': 0, 'rank_2': 0, 'rank_3': 0, 'rank_4': 0, 'rank_5': 0, 'rank_6': 0, 'rank_7': 0, 'rank_8': 0, 'rank_9': 0}),
        ),
        migrations.AlterField(
            model_name='garmentmen',
            name='combined_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='garmentothers',
            name='combined_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='garmentwomen',
            name='combined_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mengarmentscores',
            name='user_gender',
            field=models.CharField(choices=[('M', 'men'), ('W', 'women'), ('NB', 'non-binary'), ('UN', 'prefer not to say')], max_length=100),
        ),
        migrations.AlterField(
            model_name='othergarmentscores',
            name='user_gender',
            field=models.CharField(choices=[('M', 'men'), ('W', 'women'), ('NB', 'non-binary'), ('UN', 'prefer not to say')], max_length=100),
        ),
        migrations.AlterField(
            model_name='womengarmentscores',
            name='user_gender',
            field=models.CharField(choices=[('M', 'men'), ('W', 'women'), ('NB', 'non-binary'), ('UN', 'prefer not to say')], max_length=100),
        ),
    ]
