# Generated by Django 3.2.4 on 2021-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0005_auto_20210722_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mengarmentscores',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='othergarmentscores',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='womengarmentscores',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
